In [334]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler

## Load Dataset

In [335]:
def load_data(file_path):
    return pd.read_csv(file_path)

raw_file_path = "../data/raw/automobileEDA_dirty_training.csv"    
dirty_df = load_data(raw_file_path)

In [361]:
def get_shape(df):
    return df.shape

(total_rows, total_columns) = get_shape(dirty_df)

display(total_rows, total_columns)

186

48

In [337]:
dirty_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 30 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   transaction_date   203 non-null    str
 1   symboling          205 non-null    int64
 2   normalized-losses  205 non-null    int64
 3   make               203 non-null    str
 4   aspiration         205 non-null    str
 5   num-of-doors       203 non-null    str
 6   body-style         205 non-null    str
 7   drive-wheels       205 non-null    str
 8   engine-location    205 non-null    str
 9   wheel-base         205 non-null    float64
 10  length             205 non-null    float64
 11  width              205 non-null    float64
 12  height             205 non-null    float64
 13  curb-weight        205 non-null    int64
 14  engine-type        205 non-null    str
 15  num-of-cylinders   205 non-null    str
 16  engine-size        205 non-null    int64
 17  fuel-system        205 non-null    str
 18  bore               205 non-null    float64
 19  stroke             201 non-null    float64
 20  compression-ratio  205 non-null    float64
 21  horsepower         202 non-null    float64
 22  peak-rpm           205 non-null    float64
 23  city-mpg           205 non-null    int64
 24  highway-mpg        205 non-null    int64
 25  price              202 non-null    float64
 26  city-L/100km       205 non-null    float64
 27  horsepower-binned  204 non-null    str
 28  diesel             205 non-null    int64
 29  gas                205 non-null    int64
dtypes: float64(11), int64(8), str(11)
memory usage: 48.2 KB

In [302]:
dirty_df.describe()

,symboling,normalized-losses,wheel-base,length,width,height,curb-weight,engine-size,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price,city-L/100km,diesel,gas
count,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,201.000000,205.000000,202.000000,205.000000,205.000000,205.000000,202.000000,205.000000,205.000000,205.000000
mean,0.839024,122.058537,98.784878,0.837107,0.915095,53.762927,2554.575610,126.980488,3.329020,3.258209,10.207902,103.403526,5119.515800,25.200000,30.721951,13181.668317,9.939602,0.102439,0.897561
std,1.247916,31.748344,6.018632,0.059030,0.028986,2.439080,515.016952,41.398466,0.266929,0.316354,4.064078,37.453870,476.073141,6.446917,6.836734,7924.054951,2.537799,0.303967,0.303967
min,-2.000000,65.000000,86.600000,0.678039,0.837500,47.800000,1488.000000,61.000000,2.540000,2.070000,7.000000,48.000000,4150.000000,13.000000,16.000000,5118.000000,4.795918,0.000000,0.000000
25%,0.000000,101.000000,94.500000,0.801538,0.890278,52.000000,2169.000000,98.000000,3.150000,3.110000,8.600000,70.000000,4800.000000,19.000000,25.000000,7778.250000,7.833333,0.000000,1.000000
50%,1.000000,122.000000,97.000000,0.832292,0.909722,54.100000,2420.000000,120.000000,3.310000,3.290000,9.000000,95.000000,5200.000000,24.000000,30.000000,10320.000000,9.791667,0.000000,1.000000
75%,2.000000,137.000000,102.400000,0.881788,0.923611,55.500000,2926.000000,141.000000,3.580000,3.410000,9.400000,116.000000,5500.000000,30.000000,34.000000,16482.500000,12.368421,0.000000,1.000000
max,3.000000,256.000000,120.900000,1.000000,1.000000,59.800000,4066.000000,326.000000,3.940000,4.170000,23.000000,262.000000,6600.000000,49.000000,54.000000,45400.000000,18.076923,1.000000,1.000000

In [338]:
def check_head(n):
    return dirty_df.head(n)

check_head(5)

,transaction_date,symboling,normalized-losses,make,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price,city-L/100km,horsepower-binned,diesel,gas
0,2025-01-01,3,122,alfa-romero,std,two,convertible,rwd,front,88.6,...,9.0,111.0,5000.0,21,27,13495.0,11.190476,Medium,0,1
1,02/01/2025,3,122,alfa-romero,std,two,convertible,rwd,front,88.6,...,9.0,111.0,5000.0,21,27,16500.0,11.190476,Medium,0,1
2,01-03-2025,1,122,ALFA-ROMERO,std,two,hatchback,rwd,front,94.5,...,9.0,154.0,5000.0,19,26,16500.0,12.368421,Medium,0,1
3,04-Jan-2025,2,164,audi,std,four,sedan,fwd,front,99.8,...,10.0,102.0,5500.0,24,30,13950.0,9.791667,Medium,0,1
4,2025-01-05,2,164,audi,std,four,sedan,4wd,front,99.4,...,8.0,115.0,5500.0,18,22,17450.0,13.055556,Medium,0,1

## Data Cleaning

#### Removing Null Values

In [339]:
def null_value_check(df):
    null_counts = df.isnull().sum()
    dirty_df_nulls = null_counts.reset_index()
    dirty_df_nulls.columns = ['column_name', 'null_count']
    dirty_df_nulls = dirty_df_nulls[dirty_df_nulls['null_count'] > 0]

    dirty_df_nulls['data_type'] = dirty_df_nulls['column_name'].apply(lambda x: df[x].dtype)

    return dirty_df_nulls

null_value_check(dirty_df)

          column_name  null_count data_type
0    transaction_date           2       str
3                make           2       str
5        num-of-doors           2       str
19             stroke           4   float64
21         horsepower           3   float64
25              price           3   float64
27  horsepower-binned           1       str

In [340]:
dirty_df = dirty_df.dropna()
null_value_check(dirty_df)

Empty DataFrame
Columns: [column_name, null_count, data_type]
Index: []

#### Removing Duplicates

In [341]:
def duplicate_value_check(df):
    return df.duplicated().sum() / len(df)

duplicate_value_check(dirty_df)

np.float64(0.015873015873015872)

In [342]:
dirty_df = dirty_df.drop_duplicates()
duplicate_value_check(dirty_df)

np.float64(0.0)

## Data Transformation

#### Numerical Data

In [343]:
# Normalizing height column to meters
# dirty_df['height'] = dirty_df['height'] / 100
# dirty_df['height'].describe()

#### Date

In [344]:
dirty_df['transaction_date'] = pd.to_datetime(dirty_df['transaction_date'], format='mixed')
dirty_df['transaction_date'].describe()

count                    186
mean     2025-04-22 20:00:00
min      2025-01-01 00:00:00
25%      2025-03-01 06:00:00
50%      2025-04-21 12:00:00
75%      2025-06-11 12:00:00
max      2025-12-04 00:00:00
Name: transaction_date, dtype: object

#### String

In [345]:
string_cols = dirty_df.select_dtypes(include='object').columns

def normalize_string_columns(df, string_cols):    
    for col in string_cols:
        df[col] = df[col].str.lower().str.strip()

normalize_string_columns(dirty_df, string_cols)

/var/folders/hy/cmzvb1297gj8yg_krsfk8whc0000gn/T/ipykernel_42632/977074859.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  string_cols = dirty_df.select_dtypes(include='object').columns

#### Categorical

In [346]:
categories = {}

for col in string_cols:
    categories_list = pd.Categorical(dirty_df[col]).categories
    if len(categories_list) > 10: continue
    categories[col] = categories_list

categories

{'aspiration': Index(['std', 'turbo'], dtype='str'),
 'num-of-doors': Index(['four', 'two'], dtype='str'),
 'body-style': Index(['convertible', 'hardtop', 'hatchback', 'sedan', 'wagon'], dtype='str'),
 'drive-wheels': Index(['4wd', 'awd', 'fwd', 'rwd'], dtype='str'),
 'engine-location': Index(['front', 'rear'], dtype='str'),
 'engine-type': Index(['dohc', 'l', 'ohc', 'ohcf', 'ohcv'], dtype='str'),
 'num-of-cylinders': Index(['eight', 'five', 'four', 'six', 'three'], dtype='str'),
 'fuel-system': Index(['1bbl', '2bbl', 'idi', 'mfi', 'mpfi', 'spdi', 'spfi'], dtype='str'),
 'horsepower-binned': Index(['high', 'low', 'medium'], dtype='str')}

In [347]:
dirty_df['num-of-doors'] = dirty_df['num-of-doors'].map({'two': 0, 'four': 1})
dirty_df['num-of-doors'].describe()

count    186.000000
mean       0.580645
std        0.494785
min        0.000000
25%        0.000000
50%        1.000000
75%        1.000000
max        1.000000
Name: num-of-doors, dtype: float64

In [348]:
dirty_df['num-of-cylinders'] = dirty_df['num-of-cylinders'].map({'four': 4, 'six': 6, 'five': 5, 'eight': 8, 'two': 2, 'three': 3, 'twelve': 12})
dirty_df['num-of-cylinders'].describe()

count    186.000000
mean       4.349462
std        0.819640
min        3.000000
25%        4.000000
50%        4.000000
75%        4.000000
max        8.000000
Name: num-of-cylinders, dtype: float64

In [349]:
dirty_df['engine-location'] = dirty_df['engine-location'].map({'front': 0, 'rear': 1})
check_head(5)

,transaction_date,symboling,normalized-losses,make,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price,city-L/100km,horsepower-binned,diesel,gas
0,2025-01-01,3,122,alfa-romero,std,0,convertible,rwd,0,88.6,...,9.0,111.0,5000.0,21,27,13495.0,11.190476,medium,0,1
1,2025-02-01,3,122,alfa-romero,std,0,convertible,rwd,0,88.6,...,9.0,111.0,5000.0,21,27,16500.0,11.190476,medium,0,1
2,2025-01-03,1,122,alfa-romero,std,0,hatchback,rwd,0,94.5,...,9.0,154.0,5000.0,19,26,16500.0,12.368421,medium,0,1
3,2025-01-04,2,164,audi,std,1,sedan,fwd,0,99.8,...,10.0,102.0,5500.0,24,30,13950.0,9.791667,medium,0,1
4,2025-01-05,2,164,audi,std,1,sedan,4wd,0,99.4,...,8.0,115.0,5500.0,18,22,17450.0,13.055556,medium,0,1

In [350]:
dirty_df['horsepower_ordinal'] = dirty_df['horsepower-binned'].map({'low': 0, 'medium': 1, 'high': 2})
dirty_df.drop(columns=['horsepower-binned'], inplace=True)
dirty_df['horsepower_ordinal'].describe()

count    186.000000
mean       0.543011
std        0.690303
min        0.000000
25%        0.000000
50%        0.000000
75%        1.000000
max        2.000000
Name: horsepower_ordinal, dtype: float64

#### One Hot Encoding

In [351]:
dirty_df = pd.get_dummies(dirty_df, columns=['body-style'], dtype=int, prefix='body-style')
check_head(5)

,transaction_date,symboling,normalized-losses,make,aspiration,num-of-doors,drive-wheels,engine-location,wheel-base,length,...,price,city-L/100km,diesel,gas,horsepower_ordinal,body-style_convertible,body-style_hardtop,body-style_hatchback,body-style_sedan,body-style_wagon
0,2025-01-01,3,122,alfa-romero,std,0,rwd,0,88.6,0.811148,...,13495.0,11.190476,0,1,1,1,0,0,0,0
1,2025-02-01,3,122,alfa-romero,std,0,rwd,0,88.6,0.811148,...,16500.0,11.190476,0,1,1,1,0,0,0,0
2,2025-01-03,1,122,alfa-romero,std,0,rwd,0,94.5,0.822681,...,16500.0,12.368421,0,1,1,0,0,1,0,0
3,2025-01-04,2,164,audi,std,1,fwd,0,99.8,0.848630,...,13950.0,9.791667,0,1,1,0,0,0,1,0
4,2025-01-05,2,164,audi,std,1,4wd,0,99.4,0.848630,...,17450.0,13.055556,0,1,1,0,0,0,1,0

In [352]:
dirty_df = pd.get_dummies(dirty_df, columns=['drive-wheels'], dtype=int, prefix='drive-wheels')
check_head(5)

,transaction_date,symboling,normalized-losses,make,aspiration,num-of-doors,engine-location,wheel-base,length,width,...,horsepower_ordinal,body-style_convertible,body-style_hardtop,body-style_hatchback,body-style_sedan,body-style_wagon,drive-wheels_4wd,drive-wheels_awd,drive-wheels_fwd,drive-wheels_rwd
0,2025-01-01,3,122,alfa-romero,std,0,0,88.6,0.811148,0.890278,...,1,1,0,0,0,0,0,0,0,1
1,2025-02-01,3,122,alfa-romero,std,0,0,88.6,0.811148,0.890278,...,1,1,0,0,0,0,0,0,0,1
2,2025-01-03,1,122,alfa-romero,std,0,0,94.5,0.822681,0.909722,...,1,0,0,1,0,0,0,0,0,1
3,2025-01-04,2,164,audi,std,1,0,99.8,0.848630,0.919444,...,1,0,0,0,1,0,0,0,1,0
4,2025-01-05,2,164,audi,std,1,0,99.4,0.848630,0.922222,...,1,0,0,0,1,0,1,0,0,0

In [353]:
dirty_df = pd.get_dummies(dirty_df, columns=['aspiration'], dtype=int, prefix='aspiration')
check_head(5)

,transaction_date,symboling,normalized-losses,make,num-of-doors,engine-location,wheel-base,length,width,height,...,body-style_hardtop,body-style_hatchback,body-style_sedan,body-style_wagon,drive-wheels_4wd,drive-wheels_awd,drive-wheels_fwd,drive-wheels_rwd,aspiration_std,aspiration_turbo
0,2025-01-01,3,122,alfa-romero,0,0,88.6,0.811148,0.890278,48.8,...,0,0,0,0,0,0,0,1,1,0
1,2025-02-01,3,122,alfa-romero,0,0,88.6,0.811148,0.890278,48.8,...,0,0,0,0,0,0,0,1,1,0
2,2025-01-03,1,122,alfa-romero,0,0,94.5,0.822681,0.909722,52.4,...,0,1,0,0,0,0,0,1,1,0
3,2025-01-04,2,164,audi,1,0,99.8,0.848630,0.919444,54.3,...,0,0,1,0,0,0,1,0,1,0
4,2025-01-05,2,164,audi,1,0,99.4,0.848630,0.922222,54.3,...,0,0,1,0,1,0,0,0,1,0

In [354]:
dirty_df = pd.get_dummies(dirty_df, columns=['engine-type'], dtype=int, prefix='engine-type')
check_head(5)

,transaction_date,symboling,normalized-losses,make,num-of-doors,engine-location,wheel-base,length,width,height,...,drive-wheels_awd,drive-wheels_fwd,drive-wheels_rwd,aspiration_std,aspiration_turbo,engine-type_dohc,engine-type_l,engine-type_ohc,engine-type_ohcf,engine-type_ohcv
0,2025-01-01,3,122,alfa-romero,0,0,88.6,0.811148,0.890278,48.8,...,0,0,1,1,0,1,0,0,0,0
1,2025-02-01,3,122,alfa-romero,0,0,88.6,0.811148,0.890278,48.8,...,0,0,1,1,0,1,0,0,0,0
2,2025-01-03,1,122,alfa-romero,0,0,94.5,0.822681,0.909722,52.4,...,0,0,1,1,0,0,0,0,0,1
3,2025-01-04,2,164,audi,1,0,99.8,0.848630,0.919444,54.3,...,0,1,0,1,0,0,0,1,0,0
4,2025-01-05,2,164,audi,1,0,99.4,0.848630,0.922222,54.3,...,0,0,0,1,0,0,0,1,0,0

In [355]:
dirty_df = pd.get_dummies(dirty_df, columns=['fuel-system'], dtype=int, prefix='fuel-system')
check_head(5)

,transaction_date,symboling,normalized-losses,make,num-of-doors,engine-location,wheel-base,length,width,height,...,engine-type_ohc,engine-type_ohcf,engine-type_ohcv,fuel-system_1bbl,fuel-system_2bbl,fuel-system_idi,fuel-system_mfi,fuel-system_mpfi,fuel-system_spdi,fuel-system_spfi
0,2025-01-01,3,122,alfa-romero,0,0,88.6,0.811148,0.890278,48.8,...,0,0,0,0,0,0,0,1,0,0
1,2025-02-01,3,122,alfa-romero,0,0,88.6,0.811148,0.890278,48.8,...,0,0,0,0,0,0,0,1,0,0
2,2025-01-03,1,122,alfa-romero,0,0,94.5,0.822681,0.909722,52.4,...,0,0,1,0,0,0,0,1,0,0
3,2025-01-04,2,164,audi,1,0,99.8,0.848630,0.919444,54.3,...,1,0,0,0,0,0,0,1,0,0
4,2025-01-05,2,164,audi,1,0,99.4,0.848630,0.922222,54.3,...,1,0,0,0,0,0,0,1,0,0

In [356]:
def transform_features(df, columns):
    scaler = MinMaxScaler()
    df[columns] = scaler.fit_transform(df[columns])
    return df

dirty_df = transform_features(
    dirty_df, [
        'symboling', 
        'wheel-base', 
        'length', 
        'width', 
        'curb-weight', 
        'num-of-cylinders',
        'engine-size',
        'horsepower',
        'peak-rpm',
        'city-mpg',
        'highway-mpg',
        'price'
    ]
)

check_head(5)

,transaction_date,symboling,normalized-losses,make,num-of-doors,engine-location,wheel-base,length,width,height,...,engine-type_ohc,engine-type_ohcf,engine-type_ohcv,fuel-system_1bbl,fuel-system_2bbl,fuel-system_idi,fuel-system_mfi,fuel-system_mpfi,fuel-system_spdi,fuel-system_spfi
0,2025-01-01,1.0,122,alfa-romero,0,0,0.068966,0.450407,0.324786,48.8,...,0,0,0,0,0,0,0,1,0,0
1,2025-02-01,1.0,122,alfa-romero,0,0,0.068966,0.450407,0.324786,48.8,...,0,0,0,0,0,0,0,1,0,0
2,2025-01-03,0.6,122,alfa-romero,0,0,0.272414,0.489431,0.444444,52.4,...,0,0,1,0,0,0,0,1,0,0
3,2025-01-04,0.8,164,audi,1,0,0.455172,0.577236,0.504274,54.3,...,1,0,0,0,0,0,0,1,0,0
4,2025-01-05,0.8,164,audi,1,0,0.441379,0.577236,0.521368,54.3,...,1,0,0,0,0,0,0,1,0,0

In [357]:
dirty_df['make_frequency'] = dirty_df['make'].map(dirty_df['make'].value_counts(normalize=True))
dirty_df.drop(columns=['make'], inplace=True)
check_head(5)

,transaction_date,symboling,normalized-losses,num-of-doors,engine-location,wheel-base,length,width,height,curb-weight,...,engine-type_ohcf,engine-type_ohcv,fuel-system_1bbl,fuel-system_2bbl,fuel-system_idi,fuel-system_mfi,fuel-system_mpfi,fuel-system_spdi,fuel-system_spfi,make_frequency
0,2025-01-01,1.0,122,0,0,0.068966,0.450407,0.324786,48.8,0.411171,...,0,0,0,0,0,0,1,0,0,0.016129
1,2025-02-01,1.0,122,0,0,0.068966,0.450407,0.324786,48.8,0.411171,...,0,0,0,0,0,0,1,0,0,0.016129
2,2025-01-03,0.6,122,0,0,0.272414,0.489431,0.444444,52.4,0.517843,...,0,1,0,0,0,0,1,0,0,0.016129
3,2025-01-04,0.8,164,1,0,0.455172,0.577236,0.504274,54.3,0.329325,...,0,0,0,0,0,0,1,0,0,0.037634
4,2025-01-05,0.8,164,1,0,0.441379,0.577236,0.521368,54.3,0.518231,...,0,0,0,0,0,0,1,0,0,0.037634

In [358]:
display(total_rows, total_columns)

205

30

## Export

In [359]:
def export(df, file_path):
    df.to_csv(file_path, index=False)

export(dirty_df, '../data/processed/automobile_cleaned_data.csv')